# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Nicholas Tolley
tagline:          'Nicholas Tolley'
description:      'Computational Neuroscientist.<br>Personal blog and portfoloio'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Nicholas Tolley'
  url:            https://ntolley.github.io/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ntolley/ntolley.github.io/

tags:


github_username:  ntolley
linkedin_username: ntolley
